version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      npm-maintenance:
        update-types:
          - minor
          - patch
  - package-ecosystem: gradle
    directory: /apps/mobile/android
    schedule:
      interval: monthly
    groups:
      android-maintenance:
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
